# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Package-Tools
version:      0.01
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Config::IniFiles:              2.38
    ExtUtils::MakeMaker:           6.17
    File::Spec:                    0.87
    Getopt::Long:                  2.26
    Log::Log4perl:                 0.47
    Term::ANSIColor:               1.07
    Text::ParseWords:              3.2
    Text::Wrap:                    2001.0131

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
